name: CD-DEV

on:
    push:
        branches: [develop]
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

jobs:
    deploy:
        name: Download and deploy
        runs-on: ubuntu-latest
        env:
            BUCKET: acm-website-client
            BUILD_ARTIFACT: dist
            REGION: us-east-1
        steps:
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.REGION }}

            - uses: actions/download-artifact@v4
              with:
                name: ${{ env.BUILD_ARTIFACT }}
                path: ./dist

            - name: Upload to s3
              run: |
                aws s3 sync --delete ${{ env.BUILD_ARTIFACT }} s3://${{ env.BUCKET }} 