name: CD-DEV

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

jobs:
    deploy:
        name: Download and deploy
        if: github.event.workflow_run.head_branch == 'develop'
        runs-on: ubuntu-latest
        environment: development
        steps:
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - uses: actions/download-artifact@v4
              with:
                name: ${{ vars.BUILD_ARTIFACT }}
                path: ./${{ vars.BUILD_ARTIFACT }}
                github-token: ${{ github.token }}
                repository: ${{ github.repository }}
                run-id: ${{ github.event.workflow_run.id }}

            - name: Upload to s3
              run: |
                aws s3 sync --delete ./${{ vars.BUILD_ARTIFACT }} ${{ vars.S3_BUCKET_URL }} 
